[server]
enableXsrfProtection = true
folderWatchBlacklist = [".git", "dist", "build"]
port = 8501

[theme]
base = "light"
primaryColor = "#00519B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f5f5f5ff"
textColor = "#000000"
font = "Calibri"